# Generated by Django 3.1.2 on 2020-10-21 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=400, null=True)),
                ('author', models.CharField(blank=True, default='Anonymous', max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('urlToImg', models.CharField(blank=True, max_length=800, null=True)),
                ('publishedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=100)),
                ('user_fname', models.CharField(max_length=100)),
                ('user_lname', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_phone', models.DecimalField(decimal_places=0, max_digits=100)),
            ],
        ),
    ]
