# Generated by Django 3.1.2 on 2020-10-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=30)),
                ('user_fname', models.CharField(max_length=30)),
                ('user_lname', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=20)),
                ('user_address', models.TextField()),
                ('user_phone', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
