# Generated by Django 3.1.2 on 2020-10-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blognews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=400, null=True)),
                ('author', models.CharField(blank=True, default='Anonymous', max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('urlToImg', models.CharField(blank=True, max_length=800, null=True)),
                ('publishedAt', models.DateTimeField(blank=True, null=True, verbose_name='Date Published')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
