# Generated by Django 3.1.2 on 2020-10-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blognews', '0002_newsarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='publishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
